In [6]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import time
import tkinter as tk
from tkinter import messagebox

In [9]:
col = ['letter']+[f"feature_{i}" for i in range(16)]
df = pd.read_csv('2_letter_recognition.data', names=col)
df

,letter,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [10]:
label_encoder = LabelEncoder()
df['letter'] = label_encoder.fit_transform(df['letter'])
X = df.drop(['letter'], axis=1)
y = df['letter']

In [11]:
X

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15
0,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [12]:
y

0        19
1         8
2         3
3        13
4         6
         ..
19995     3
19996     2
19997    19
19998    18
19999     0
Name: letter, Length: 20000, dtype: int32

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
def create_dnn_model():
    model = Sequential()
    model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(26, activation='softmax'))  # 26 output neurons for 26 letter classes
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [15]:
start_time = time.time()
model = create_dnn_model()
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=2)  # Train silently
train_time = time.time() - start_time
train_time

Epoch 1/50

C:\Users\omkar\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:86: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 - 3s - 5ms/step - accuracy: 0.5382 - loss: 1.6680
Epoch 2/50
500/500 - 1s - 1ms/step - accuracy: 0.7398 - loss: 0.9093
Epoch 3/50
500/500 - 1s - 1ms/step - accuracy: 0.7837 - loss: 0.7492
Epoch 4/50
500/500 - 1s - 1ms/step - accuracy: 0.8117 - loss: 0.6401
Epoch 5/50
500/500 - 1s - 1ms/step - accuracy: 0.8293 - loss: 0.5719
Epoch 6/50
500/500 - 1s - 1ms/step - accuracy: 0.8494 - loss: 0.5058
Epoch 7/50
500/500 - 1s - 1ms/step - accuracy: 0.8576 - loss: 0.4642
Epoch 8/50
500/500 - 1s - 1ms/step - accuracy: 0.8714 - loss: 0.4254
Epoch 9/50
500/500 - 1s - 1ms/step - accuracy: 0.8811 - loss: 0.3934
Epoch 10/50
500/500 - 1s - 2ms/step - accuracy: 0.8869 - loss: 0.3714
Epoch 11/50
500/500 - 1s - 1ms/step - accuracy: 0.8958 - loss: 0.3397
Epoch 12/50
500/500 - 1s - 1ms/step - accuracy: 0.8976 - loss: 0.3248
Epoch 13/50
500/500 - 1s - 1ms/step - accuracy: 0.9078 - loss: 0.2936
Epoch 14/50
500/500 - 1s - 1ms/step - accuracy: 0.9121 - loss: 0.2773
Epoch 15/50
500/500 - 1s - 1ms/step - accuracy: 0.9155 - loss: 0.2688
Epoch 16/50
500/500 - 1s - 1ms/step - accuracy: 0.9186 - loss: 0.2558
Epoch 17/50
500/500 - 1s - 1ms/step - accuracy: 0.9199 - loss: 0.2458
Epoch 18/50
500/500 - 1s - 1ms/step - accuracy: 0.9285 - loss: 0.2281
Epoch 19/50
500/500 - 1s - 1ms/step - accuracy: 0.9292 - loss: 0.2185
Epoch 20/50
500/500 - 1s - 1ms/step - accuracy: 0.9342 - loss: 0.2074
Epoch 21/50
500/500 - 1s - 1ms/step - accuracy: 0.9338 - loss: 0.2037
Epoch 22/50
500/500 - 1s - 1ms/step - accuracy: 0.9373 - loss: 0.1939
Epoch 23/50
500/500 - 1s - 1ms/step - accuracy: 0.9412 - loss: 0.1839
Epoch 24/50
500/500 - 1s - 1ms/step - accuracy: 0.9419 - loss: 0.1790
Epoch 25/50
500/500 - 1s - 1ms/step - accuracy: 0.9434 - loss: 0.1733
Epoch 26/50
500/500 - 1s - 1ms/step - accuracy: 0.9443 - loss: 0.1709
Epoch 27/50
500/500 - 1s - 1ms/step - accuracy: 0.9471 - loss: 0.1588
Epoch 28/50
500/500 - 1s - 1ms/step - accuracy: 0.9507 - loss: 0.1542
Epoch 29/50
500/500 - 1s - 1ms/step - accuracy: 0.9503 - loss: 0.1463
Epoch 30/50
500/500 - 1s - 1ms/step - accuracy: 0.9496 - loss: 0.1501
Epoch 31/50
500/500 - 1s - 1ms/step - accuracy: 0.9514 - loss: 0.1418
Epoch 32/50
500/500 - 1s - 1ms/step - accuracy: 0.9532 - loss: 0.1394
Epoch 33/50
500/500 - 1s - 1ms/step - accuracy: 0.9548 - loss: 0.1336
Epoch 34/50
500/500 - 1s - 1ms/step - accuracy: 0.9565 - loss: 0.1274
Epoch 35/50
500/500 - 1s - 1ms/step - accuracy: 0.9568 - loss: 0.1263
Epoch 36/50
500/500 - 1s - 1ms/step - accuracy: 0.9556 - loss: 0.1280
Epoch 37/50
500/500 - 1s - 1ms/step - accuracy: 0.9599 - loss: 0.1175
Epoch 38/50
500/500 - 1s - 1ms/step - accuracy: 0.9589 - loss: 0.1170
Epoch 39/50
500/500 - 1s - 1ms/step - accuracy: 0.9590 - loss: 0.1172
Epoch 40/50
500/500 - 1s - 1ms/step - accuracy: 0.9617 - loss: 0.1127
Epoch 41/50
500/500 - 1s - 1ms/step - accuracy: 0.9667 - loss: 0.1026
Epoch 42/50
500/500 - 1s - 1ms/step - accuracy: 0.9666 - loss: 0.1010
Epoch 43/50
500/500 - 1s - 2ms/step - accuracy: 0.9608 - loss: 0.1093
Epoch 44/50
500/500 - 1s - 1ms/step - accuracy: 0.9652 - loss: 0.0981
Epoch 45/50
500/500 - 1s - 1ms/step - accuracy: 0.9621 - loss: 0.1062
Epoch 46/50
500/500 - 1s - 1ms/step - accuracy: 0.9657 - loss: 0.0968
Epoch 47/50
500/500 - 1s - 2ms/step - accuracy: 0.9666 - loss: 0.0960
Epoch 48/50
500/500 - 1s - 1ms/step - accuracy: 0.9685 - loss: 0.0909
Epoch 49/50
500/500 - 1s - 1ms/step - accuracy: 0.9654 - loss: 0.0980
Epoch 50/50
500/500 - 1s - 1ms/step - accuracy: 0.9713 - loss: 0.0831

37.710005044937134

In [18]:
model_name = "model_2.1_MultiClass_OCR.h5"
model.save(model_name)

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [19]:
model.save("model_2.1_MultiClass_OCR.keras")

In [20]:
model = load_model(model_name)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [21]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}")

Test loss: 0.1951, Test accuracy: 0.9440

In [22]:
alphabet_dict = {i: chr(i + 65) for i in range(26)}

In [23]:
def classify_new_input(new_input):
    # Convert new input to numpy array and reshape it
    new_input = np.array(new_input).reshape(1, -1)
    # Make prediction using the trained model
    start_time = time.time()
    prediction = model.predict(new_input)
    end_time = time.time()
    pred_time = end_time - start_time
    print(f"Prediction Time : {pred_time}")
    # Inverse transform the predicted label to get the class
    predicted_class = label_encoder.inverse_transform([np.argmax(prediction)])
    return predicted_class[0]

def predict_class():
    # Get user input from entry fields
    try:
        input_values = [int(entry.get()) for entry in entry_fields]
        predicted_class = classify_new_input(input_values)
        messagebox.showinfo("Prediction", f"Predicted class: {predicted_class}")
    except ValueError:
        messagebox.showerror("Error", "Please enter valid integer values.")

In [ ]:
root = tk.Tk()
root.title("Letter Recognition Predictor")

entry_fields = []
for i in range(16):
    label = tk.Label(root, text=f"Input {i+1}:")
    label.grid(row=i, column=0, padx=10, pady=5)
    entry = tk.Entry(root)
    entry.grid(row=i, column=1, padx=10, pady=5)
    entry_fields.append(entry)

# Create predict button
predict_button = tk.Button(root, text="Predict", command=predict_class)
predict_button.grid(row=16, column=0, columnspan=2, pady=10)

# print(f"Training time: {train_time:.2f} seconds")

root.mainloop()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
Prediction Time : 0.15384936332702637